export const BRAND = {
  name: "FollowerSpike",
  promise:
    "Your LinkedIn presence on autopilot — relevant posts, comments, and connections, daily.",
  socialProof: "1,200+ founders",
  trialDays: 14,
  consentVersion: "2026-05-15",
} as const;

export const ROUTES = {
  home: "/",
  pricing: "/pricing",
  login: "/login",
  signup: "/signup",
  callback: "/callback",
  app: "/app",
  audit: "/tools/linkedin-audit",
  trust: "/trust",
  security: "/security",
  privacy: "/privacy",
  terms: "/terms",
  dpa: "/dpa",
  subprocessors: "/subprocessors",
} as const;

export type SubscriptionTier = "free" | "starter" | "pro" | "scale";
export type ApprovalMode = "review" | "auto" | "off";
export type AutomationAction = "post" | "comment" | "invite" | "like" | "withdraw" | "profile_scrape";

export const PRICING = [
  {
    tier: "starter",
    name: "Starter",
    monthlyInr: "₹799",
    monthlyUsd: "$9",
    annualUsd: "$90",
    planEnv: "RAZORPAY_PLAN_STARTER",
    popular: false,
    description: "For professionals who need consistent posts without living in LinkedIn.",
    limits: { posts: 1, comments: 5, invites: 5, likes: 15 },
    features: [
      "1 AI post per day",
      "5 relevance-scored comments per day",
      "Profile audit and rebuild plan",
      "Approval queue",
      "Email digest",
    ],
  },
  {
    tier: "pro",
    name: "Pro",
    monthlyInr: "₹1,999",
    monthlyUsd: "$19",
    annualUsd: "$190",
    planEnv: "RAZORPAY_PLAN_PRO",
    popular: true,
    description: "For founders, CEOs, and consultants turning LinkedIn into a daily growth channel.",
    limits: { posts: 2, comments: 15, invites: 15, likes: 40 },
    features: [
      "Founder voice learning",
      "15 human-review comments per day",
      "Target leader tracking",
      "Risk-managed autopilot",
      "Priority support",
    ],
  },
  {
    tier: "scale",
    name: "Scale",
    monthlyInr: "₹3,999",
    monthlyUsd: "$39",
    annualUsd: "$390",
    planEnv: "RAZORPAY_PLAN_SCALE",
    popular: false,
    description: "For operators and agencies running a tighter executive presence workflow.",
    limits: { posts: 3, comments: 30, invites: 25, likes: 70 },
    features: [
      "Scale-level daily limits",
      "Advanced target lists",
      "Autopilot safety center",
      "WhatsApp-ready digest hooks",
      "Exportable activity logs",
    ],
  },
] as const;

export const INDUSTRIES = [
  "SaaS",
  "Fintech",
  "E-commerce",
  "Real Estate",
  "Healthcare",
  "EdTech",
  "Crypto and Web3",
  "AI and Machine Learning",
  "Cybersecurity",
  "Marketing Agencies",
  "Consulting",
  "Legal Services",
  "Manufacturing",
  "Logistics and Supply Chain",
  "HR and Recruiting",
  "Insurance",
  "Coaching and Personal Development",
  "Media and Publishing",
  "Hospitality and Travel",
  "CleanTech and Sustainability",
] as const;

export const CITIES = [
  "New York",
  "San Francisco",
  "Los Angeles",
  "Austin",
  "Chicago",
  "Boston",
  "Seattle",
  "Miami",
  "Toronto",
  "London",
  "Berlin",
  "Amsterdam",
  "Paris",
  "Dublin",
  "Lisbon",
  "Barcelona",
  "Bangalore",
  "Mumbai",
  "Delhi",
  "Singapore",
  "Dubai",
  "Tel Aviv",
  "Sydney",
  "Tokyo",
  "Sao Paulo",
] as const;

export const ROLES = [
  "Founder",
  "Co-founder",
  "CEO",
  "Solo Founder",
  "Indie Hacker",
  "Startup CTO",
  "Product Manager",
  "Head of Marketing",
  "VP Sales",
  "Chief Revenue Officer",
  "Growth Lead",
  "Sales Director",
  "Business Development Manager",
  "Consultant",
  "Agency Owner",
  "Freelancer",
  "Executive Coach",
  "Career Coach",
  "Investor or VC",
  "Angel Investor",
  "Recruiter",
  "Real Estate Agent",
  "Financial Advisor",
  "Content Creator",
  "Personal Brand Builder",
] as const;

export const TRUST_DISCLAIMER =
  "FollowerSpike is not affiliated with, endorsed by, or certified by LinkedIn. Automation carries platform risk; FollowerSpike is designed with consent, review, rate limits, and pause controls to reduce that risk.";
